import { Router } from "express";
import appNotificationRoutes from "../modules/appNotifications/appNotification.routes.js";
import authRoutes from "../modules/auth/auth.routes.js";
import branchRoutes from "../modules/branch/branch.routes.js";
import staffRoutes from "../modules/staff/staff.routes.js";
import memberRoutes from "../modules/member/member.routes.js";
import planRoutes from "../modules/plans/plan.routes.js";
import publicAttendanceRoutes from "../modules/attendance/publicAttendance.routes.js";
import classRoutes from "../modules/classes/class.routes.js";
import paymentRoutes from "../modules/payments/payment.routes.js";
import publicPaymentRoutes from "../modules/payments/publicPayment.routes.js";
import dashboardRoutes from "../modules/dashboard/dashboard.routes.js";
import alertRoutes from "../modules/alert/alert.routes.js";
import expenseRoutes from "../modules/expenses/expense.routes.js";
import dietRoutes from "../modules/diet/diet.routes.js";
import workoutRoutes from "../modules/workout/workout.routes.js";
import notifRoutes from "../modules/notifications/notif.routes.js";
import invoiceRoutes from "../modules/invoice/invoice.routes.js";
import financeRoutes from "../modules/finance/finance.routes.js";
import inventoryRoutes from "../modules/inventory/inventory.routes.js";
import purchaseRoutes from "../modules/purchase/purchase.routes.js";
import sessionRoutes from "../modules/session/session.routes.js";
import MemberPlan from "../modules/memberplan/memberPlan.routes.js";
import memberPlanAssignmentRoutes from "../modules/memberPlanAssignment/memberPlanAssignment.routes.js";
import SalaryRoutes from "../modules/salary/salary.routes.js";
import houseKeepingRoutes from "../modules/houseKeppingtask/housekeepingtask.routes.js";
import staffAttendanceRoutes from "../modules/staffAttendance/staffAttendance.routes.js";
import housekeepingDashboardRoutes from "../modules/dashboard/housekeepingdashboard.routes.js";
import generaltrainerRoutes from "../modules/generaltrainer/generalTrainer.routes.js";
import memberAttendenceRoutes from "../modules/memberattendence/attendence.routes.js";
import shiftRoutes from "../modules/shift/shift.routes.js";
import bookingRoutes from "../modules/classbookingrequest/classbooking.routes.js";
// import housekeepingAttendance from "../modules/housekeepingAttendance/housekeepingattendance.routes.js";
import memberDeshboardRoutes from "../modules/member/memberDashboard.routes.js";
import adminStaffAttendanceRoutes from "../modules/adminStaffAttendance/adminStaffAttendance.routes.js";
import memberSelfRoutes from "../modules/member/memberSelf.routes.js";
import personalTrainerDashboardRoutes from "../modules/dashboard/personalTrainerDashboard.routes.js";
import reportsRoutes from "../modules/reports/reports.routes.js";
import adminSettingsRoutes from "../modules/appSettings/appSetting.routes.js";
import leadRoutes from "../modules/leads/lead.routes.js";
import healthRoutes from "../modules/health/health.routes.js";
import subadminRoutes from "../modules/subadmin/subadmin.routes.js";
import globalSettingRoutes from "../modules/globalSettings/globalSetting.routes.js";
import assessmentRoutes from "../modules/assessment/assessment.routes.js";
import leaderboardRoutes from "../modules/leaderboard/leaderboard.routes.js";
import bodybuildingRoutes from "../modules/bodybuilding/bodybuilding.routes.js";
import receptionistDashboardRoutes from "../modules/dashboard/receptionistDashboard.routes.js";
import equipmentRoutes from "../modules/inventory/equipment.routes.js";
import automationRoutes from "../modules/appSettings/automation.routes.js";
import creditsRoutes from "../modules/credits/credits.routes.js";
import messageTemplateRoutes from "../modules/messageTemplates/messageTemplate.routes.js";
import integrationsRoutes from "../modules/integrations/integrations.routes.js";
import supportRoutes from "../modules/support/support.routes.js";

const router = Router();

// test route
router.get("/ping", (req, res) => {
  res.json({ status: "ok" });
});

router.use("/auth", authRoutes);
router.use("/branches", branchRoutes);
router.use("/staff", staffRoutes);
router.use("/members", memberRoutes);
router.use("/plans", planRoutes);
router.use("/attendance/public", publicAttendanceRoutes);
router.use("/class", classRoutes);
router.use("/payments", paymentRoutes);
router.use("/payments/public", publicPaymentRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/memberattendence", memberAttendenceRoutes);
router.use("/alerts", alertRoutes);
router.use("/expenses", expenseRoutes);
router.use("/finance", financeRoutes);
router.use("/diet", dietRoutes);
router.use("/workout", workoutRoutes);
router.use("/notif", notifRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/purchases", purchaseRoutes);
router.use("/MemberPlan", MemberPlan);
router.use("/member-plan-assignments", memberPlanAssignmentRoutes);
router.use("/sessions", sessionRoutes);
router.use("/salaries", SalaryRoutes);
router.use("/housekeepingtask", houseKeepingRoutes);
router.use("/staff-attendance", staffAttendanceRoutes);
router.use("/housekeepingdashboard", housekeepingDashboardRoutes);
router.use("/generaltrainer", generaltrainerRoutes);
router.use("/shift", shiftRoutes);
router.use("/personal-trainer-dashboard", personalTrainerDashboardRoutes);
// router.use("/housekeeping-attendance", housekeepingAttendance);
router.use("/member-dashboard", memberDeshboardRoutes);
router.use("/admin-staff-attendance", adminStaffAttendanceRoutes);
router.use("/member-self", memberSelfRoutes);
router.use("/reports", reportsRoutes);
router.use("/booking", bookingRoutes);
router.use("/adminSettings", adminSettingsRoutes);
router.use("/leads", leadRoutes);
router.use("/health", healthRoutes);
router.use("/v1/health", healthRoutes);
router.use("/subadmins", subadminRoutes);
router.use("/global-settings", globalSettingRoutes);
router.use("/v1/assessments", assessmentRoutes);
router.use("/v1/leaderboard", leaderboardRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/v1/bodybuilding", bodybuildingRoutes);
router.use("/receptionist-dashboard", receptionistDashboardRoutes);
router.use("/v1/equipment", equipmentRoutes);
router.use("/v1/automation", automationRoutes);
router.use("/v1/credits", creditsRoutes);
router.use("/app-notifications", appNotificationRoutes);
router.use("/v1/message-templates", messageTemplateRoutes);
router.use("/integrations", integrationsRoutes);
router.use("/support", supportRoutes);

export default router;
